// actionTypes.js
// get
export const GET_TODOLIST_REQUEST = "GET_TODOLIST_REQUEST";
export const GET_TODOLIST_SUCCESS = "GET_TODOLIST_SUCCESS";
export const GET_TODOLIST_FAILURE = "GET_TODOLIST_FAILURE";
// delete
export const DELETE_LIST_ITEM_REQUEST = "DELETE_LIST_ITEM_REQUEST";
export const DELETE_LIST_ITEM_SUCCESS = "DELETE_LIST_ITEM_SUCCESS";
export const DELETE_LIST_ITEM_FAILURE = "DELETE_LIST_ITEM_FAILURE";
// add
export const ADD_NEW_LIST_ITEM_REQUEST = "ADD_NEW_LIST_ITEM_REQUEST";
export const ADD_NEW_LIST_ITEM_SUCCESS = "ADD_NEW_LIST_ITEM_SUCCESS";
export const ADD_NEW_LIST_ITEM_FAILURE = "ADD_NEW_LIST_ITEM_FAILURE";
// update
export const UPDATE_LIST_ITEM_REQUEST = "UPDATE_LIST_ITEM_REQUEST";
export const UPDATE_LIST_ITEM_SUCCESS = "UPDATE_LIST_ITEM_SUCCESS";
export const UPDATE_LIST_ITEM_FAILURE = "UPDATE_LIST_ITEM_FAILURE";
